spring.application.name=CollegeDB
# Database connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/collegedb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=Blackbadger@9

# Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show INFO logs
logging.level.root=INFO

# If you want DEBUG logs too (more detailed):
logging.level.com.example.collegedb=DEBUG

# Server port
server.port=${SERVER_PORT:8080}
